//ANIMES REDUCER TYPES
export const GET_ANIMES = 'GET_ANIMES';
export const GET_ANIME_DETAILS = 'GET_ANIME_DETAILS';

//AUTH REDUCER TYPES
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILED = 'LOAD_PROFILE_FAILED';

//MESSAGES REDUCER TYPES
export const ADD_SUCCESS_MESSAGE = 'ADD_SUCCESS_MESSAGE';
export const ADD_WARNING_MESSAGE = 'ADD_WARNING_MESSAGE';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const FLUSH_MESSAGES = 'FLUSH_MESSAGES';