//ANIMES REDUCER TYPES
export const GET_ANIMES = 'GET_ANIMES';
export const GET_ANIME_DETAILS = 'GET_ANIME_DETAILS';

//AUTH REDUCER TYPES
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILED = 'LOAD_PROFILE_FAILED';

//MESSAGES REDUCER TYPES
export const ADD_SUCCESS_MESSAGE = 'ADD_SUCCESS_MESSAGE';
export const ADD_WARNING_MESSAGE = 'ADD_WARNING_MESSAGE';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const FLUSH_MESSAGES = 'FLUSH_MESSAGES';

//FILTERING REDUCER TYPES
export const FILTERING_SUCCESS = 'FILTERING_SUCCESS';
export const FILTERING_FAILED = 'FILTERING_FAILED';
export const FILTERING_FLUSH = 'FILTERING_FLUSH';
export const SET_SEARCH_LINE = 'SET_SEARCH_LINE';
export const CLEAR_SEARCH_LINE = 'CLEAR_SEARCH_LINE';
export const ADD_GENRE = 'ADD_GENRE';
export const REMOVE_GENRE = 'REMOVE_GENRE';
export const ADD_TYPE = 'ADD_TYPE';
export const REMOVE_TYPE = 'REMOVE_TYPE';
export const ADD_PRODUCER = 'ADD_PRODUCER';
export const REMOVE_PRODUCER = 'REMOVE_PRODUCER';